#+STARTUP: showall

* 구조
  줄의 시작부에 공백 없이 *를 입력하고 한 칸을 띄우면 제목이 된다.

** 주제
    추가로 *를 더 입력한 수만큼 단계를 정할 수 있으며 입력이 끝난 다음 M-left,
    M-right로 단계를 조절할 수 있다. M-S-left, M-S-right로 하위 항목들에 대해
    일괄적으로 변경이 가능하다.

** 이동
    C-c C-n, C-c C-p를 이용하여 제목들 사이의 이동이 가능하다. 제목 위에서 TAB
    키를 누르면 하위 항목을 접고 펴는게 가능하고, S-TAB으로 모든 제목에 대해
    같은 동작을 행할 수 있다.

** 순서 변경
    M-up, M-down으로 단위별 순서 변경이 가능하다.

** 목록
*** 번호 없는 목록
    - 문장의 시작에 -를 입력하고 한 칸을 띄우면 목록이 된다.
    - 한 항목의 끝에서 M-RET을 입력하면 다음 내용을 입력할 수 있다.
      - M-RET 다음 TAB을 입력하면 들여쓰기가 가능하다.
    - 들여쓰기 단계를 조절하기 위한 방법은 제목과 동일하다.
    - 순서 변경도 제목과 동일하다.
    - S-left, S-right로 스타일 변경이 가능하다.

*** 번호 있는 목록
    1) 문장의 시작에 0. 또는 0) 등의 형식을 적으면 된다.

*** 확인 목록 [1/5]
    - [ ] 시작부에 [ ]를 입력하면 확인 목록을 작성할 수 있다.
    - [ ] 항목 끝에서 M-S-RET를 입력하여 새 항목을 추가한다.
    - [X] C-c C-c를 입력하면 X 표기가 가능하다.
    - [-] 하위 항목을 만들 수 있다.
      - [ ] 상위 항목에서 X 표기가 불가능해진다.
      - [X] 하위 항목들의 집계가 자동으로 반영된다.
    - [ ] 확인 내용을 추적하기 위해서는 상위 단계에 [0/0]을 입력하면 된다.

*** 정의 목록
    - 대상1 :: 설명1
    - 대상2 :: 설명2


* 서식
** 간단한 서식
    - /이탤릭/
    - *볼드*
    - _밑줄_
    - =리터럴=
    - ~코드~

** 블록
    #+BEGIN_EXAMPLE
      예제 블록
    #+END_EXAMPLE

    #+BEGIN_QUOTE
    인용 블록
    #+END_QUOTE

    #+BEGIN_CENTER
    출력시 가운데 위치하는 블록
    #+END_CENTER

    블록은 <를 입력한 다음 선택자를 적고 TAB을 누르면 템플릿을 통해 쉽게 만들 수
    있다. 선택자는 블록 종류를 나타내는 단어의 첫글자를 소문자로 적어준다.

    #+BEGIN_EXAMPLE
      <eTAB
      <qTAB
      <cTAB
    #+END_EXAMPLE

** 코드 블록
    <sTAB을 입력해서 템플릿을 통해 블록을 생성하고 언어 이름을 적어준다.

    #+BEGIN_SRC python
      print('hello world')
    #+END_SRC

    설정파일에 언어 목록을 추가하면 코드블록 내에서 C-c C-c를 입력해서 결과를
    출력할 수 있다.

    #+BEGIN_SRC python :results output
      print('hello world')
    #+END_SRC

    #+RESULTS:
    : hello world

    #+BEGIN_SRC elisp
      (org-babel-do-load-languages
       `org-babel-load-langusges
       `(
         (python . t)
         ))
    #+END_SRC

** 링크
    - C-u C-c C-l을 입력해서 파일에 대한 링크를 만들 수 있다.
    - C-c C-l을 입력하면 여러가지 외부 링크를 만들 수 있고, *에 띄어쓰기 없이
      제목을 적으면 내부 링크가 만들어진다.
    - 링크 위에서 C-c C-o를 입력하거나 마우스로 클릭해서 대상을 열 수 있다.


* 표
  외곽선과 컬럼을 구분하는 선은 |로, 머리글과의 구분은 ---로 표현하여 표를
  만든다.

  1) 머리글 행에서 마지막 열 이름을 적은 다음 TAB을 누르면 남은 외곽선이
     자동으로 입력되고 다음 열이 만들어진다.
  2) 이전 행으로 이동한 다음 C-c -로 머리글 행 구분선을 추가할 수 있다.
  3) TAB을 눌러 다음 칸으로 이동하거나 행을 확장할 수 있다.
  4) 행이나 열을 바꿀 때는 M-arrow를, 추가하거나 삭제할 때는 M-S-arrow를
     사용하면 된다.

     | id |  a |  b |  c |
     |----+----+----+----|
     |  1 | 10 | 20 | 30 |
     |  2 | 11 | 22 | 33 |
     |  3 | 22 | 33 | 44 |

** 표 생성과 출력
    - 비어있는 표를 생성하기 위해서는 C-c |를 입력하고 크기를 지정하면 된다.
    - 아래와 같이 공백으로 구분되어있는 표 형식의 내용을 선택한 다음 C-c |를
      입력하면 표로 변환이 된다.
      #+BEGIN_EXAMPLE
        id  a  b  c
         1 10 20 30
         2 11 22 33
         3 22 33 44
      #+END_EXAMPLE
    - 표 위에서 M-x org-table-export를 통해 파일로 출력할 수 있다.

** 간단한 계산
    - 계산을 원하는 열에서 C-c +를 입력하면 합을 구할 수 있다.
    - S-RET를 입력하면 현재 칸의 1 증가된 값을 아래 행에 덮어쓴다.
