#+OPTIONS: whn:nil
* 2018-06-12

  아직 다른 편집기에서 사용하던 기능들이 이맥스에는 어떻게 구현되어 있는지 잘
  모르는데다 단축키도 익숙하지 않아서 단순히 써 내려가는 수준 이상으로 사용을
  못하고 있다. Org 모드로 설정파일과 간단한 메모 몇 개를 남겨보기도 했지만
  일상이 아니다 보니 들여쓰기만 조금 편한 메모장 정도로만 활용중이다. 처음
  익혔던 키를 시작으로 변화가 생길 때마다 글로 남겨보면 좋을 것 같아 오늘부터
  이맥스 사용을 글로 남겨본다. 이제 막 시작한 것처럼..

  데스크탑 환경에서 따로 설정을 손대지 않고 처음 이맥스를 실행하면 메뉴바와
  툴바를 볼 수 있고, 그게 없더라도 프레임의 인터페이스를 통해 직관적으로 누구나
  종료 정도는 할 수 있다. 하지만 불가능한 경우를 제외하고 키보드만을 사용하는
  것을 목표로 하는 중이기 때문에 편집기 계통의 프로그램에서 볼 수 있는 기본적인
  기능부터 익숙해져야만 했다.
  일단 종료는 C-x C-c 이다. 처음엔 이 명령도 뭐가 먼저인지 헷갈렸지만 C-x 계열의
  명령인 것을 눈치 챈 뒤로는 쉽게 기억을 해냈다. 그 뒤로 저장을 하는게 가장
  중요한 일이었는데, 파일을 여는 습관이 '드래그&드랍'이었기 때문이다. 저장도 C-x
  로 시작하는 명령이고 C-s 를 연이어 입력하면 된다는 것은 의미로부터 추론하기가
  쉽다.
  커서를 이동하는 여러 방법의 명령이 있지만 화살표 키를 사용하는 것도 하나의
  방법이다. 이만큼이면 명령 키를 잘 사용하지 않는, 마우스로 컴퓨터를 배운
  누구라도 시작을 권할만 할 정도로 이맥스는 초보자에게 친화적이다.
  여기까지만 익히고 사용을 좀 하다보면 다른 파일을 열거나 새로운 파일을 만드는
  기능을 찾게 되는데 모두 C-x C-f 로 파일이 없는 경우 저장시에 사용할 이름과
  경로를 미리 지정해 놓는다.

  리눅스를 접해본 경험이 있는 사람 중 특별하지 않은 대다수가 한 번쯤은 봤을 ~로
  끝나는 파일들이 이제 여기저기 만들어지기 시작했다. 상당히 중요할 수도 있는
  백업 파일인데도 없애버리고 싶은 심정이 가득하다. 만들어낸 녀석이 관리할 수도
  있겠지 하고 일단 넘어간다.

  컴퓨터에 어느정도 익숙한 사람이라면 대상에 상관 없이 자주 사용하는 몇가지 키에
  대해서는 상당한 연습이 필요했다. 영역 지정에 대해서는 마우스로 해결을 하더라도
  복사, 잘라내기 붙여넣기는 시냅스에 분기 학습을 시켜야 되는 큰 작업이었다.
  각각은 M-w, C-w, C-y 인데 이맥스에서 삭제와 구분되는 제거에 관련된 기능이다.
  여기에 되돌리기 명령인 C-/ 까지만 기억하면 메모장 정도는 대체할 수 있게 된다.

** 오늘의 명령 모음

   | Key     | Function                   |
   |---------+----------------------------|
   | C-x C-c | save-buffers-kill-terminal |
   | C-x C-s | save-buffer                |
   | C-x C-f | find-file                  |
   | M-w     | kill-ring-save             |
   | C-w     | kill-region                |
   | C-y     | yank                       |
   | C-/     | undo                       |
