#+OPTIONS: whn:nil
* 2018-06-13

  편집기로 내용 작성을 어느정도 하다보면 같은 줄의 시작과 끝으로 이동하는 경우가
  빈번하게 발생한다. 이맥스는 Home, End 키를 사용해도 의도한 동작을 실행하지만
  C-a, C-e 명령에 익숙해지면 손가락의 이동을 크게 하지 않고도 같은 결과를 볼 수
  있다. 줄의 시작부에서 공백이 아닌 문자가 처음 입력된 위치로 가는 명령인 M-m도
  있기 때문에 경우에 따라 원하는 행위를 구분지을 수 있다. 커서를 옮기는 작업이
  때로는 단어 또는 단어를 구성하는 특정 문자 위치로의 이동에서 기인하는데, 단어
  단위의 이동은 M-f, M-b 명령을 사용하면 된다. 유사하게 C-b, C-f 명령은 좌우
  화살표 키와 같은 동작을 하며, C-p, C-n 명령은 상하 화살표 키와 같다. 오타
  수정이나 내용 변경을 위한 목적으로 커서를 이동하였다면 이때 단어 단위의 삭제
  명령인 M-DEL, M-d 를 사용하면 된다. C-d 명령으로 커서 위의 글자를 지울 수도
  있다. 커서가 있는 줄에서 커서 뒤의 모든 내용을 지우고 싶을 때에는 C-k 명령을
  입력하면 된다.

  이맥스는 프레임' 안의 '윈도우'를 통해 '버퍼'를 보여주는 편집기이다. 요즘의
  많은 편집기들이 보여주는 탭의 기능은 윈도우를 추가하거나 버퍼를 변경해주는
  방식으로 대체할 수 있다. C-x 2, C-x 3 명령을 통해 윈도우를 수평 또는 수직으로
  나눌 수 있으며, C-x o 명령으로 윈도우들을 순회한다. 커서가 있는 윈도우를 닫을
  때는 C-x 0, 반대로 커서가 있는 윈도우만 제외하고 모두 닫을 때는 C-x 1 명령을
  사용한다. 실수로 ESC를 세 번 연타하면 나머지 창이 모두 닫힌다.
  윈도우에 보여줄 버퍼를 변경하는 명령은 C-x b 이다. 버퍼의 이름은 TAB 키를 통해
  자동완성을 할 수 있으며, 아무 것도 입력하지 않은 상태에서 TAB 키를 누른 경우
  버퍼 목록을 확인할 수 있다. 대안 목록에서의 대상 이동에 사용하는 M-n, M-p
  명령은 버퍼 이름을 입력하는데도 유용하게 사용할 수 있다. 버퍼 선택 작업의
  취소는 C-g 명령으로 할 수 있으며, 이 명령은 이맥스에서 어떤 상황에서도 취소로
  동작한다.
  편집이 끝났거나 필요가 없어서 버퍼를 닫길 원할 때 사용하는 명령은 C-x k 이다.
  선택된 버퍼는 내용 변경 여부에 따라 저장하지 않고 닫을 것인지를 물어본다.

** 오늘의 명령 모음

   | Key   | Function               |
   |-------+------------------------|
   | C-a   | move-beginning-of line |
   | C-e   | move-end-of-line       |
   | M-m   | back-to-indentation    |
   | M-f   | forward-word           |
   | M-b   | backward-word          |
   | C-f   | forward-char           |
   | C-b   | backward-char          |
   | C-n   | next-line              |
   | C-p   | previous-line          |
   | M-DEL | backward-kill-word     |
   | M-d   | kill-word              |
   | C-d   | delete-char            |
   | C-k   | kill-line              |
   | C-x 2 | split-window-below     |
   | C-x 3 | split-window-right     |
   | C-x o | other-window           |
   | C-x 0 | delete-window          |
   | C-x 1 | delete-other-windows   |
   | C-x b | switch-to-buffer       |
   | M-n   |                        |
   | M-p   |                        |
   | C-g   | keyboard-quit          |
   | C-x k | kill-buffer            |
