* 2018-06-14

  영역을 선택하여 내용을 재구성하는 작업은 문서 편집 과정에서 빈번하게 발생한다.
  보통 넓은 영역을 직관적으로 선택하는데 마우스 사용이 편하기도 하지만 공백이나
  글자의 경계에서는 키보드 사용이 훨씬 편리하고, 선택할 영역의 시작이나 끝에
  커서가 있는 경우에도 마우스로 손을 옮기는 행위가 번거롭게 느껴진다. 이맥스도
  Shift 키와의 조합으로 영역 선택이 가능하지만, 마크를 지정하는 명령인 C-SPC 를
  시작으로 이맥스의 이동 명령을 통해 선택 영역을 확장하는 방법을 주로 사용한다.
  이맥스에서는 커서가 있는 위치의 왼쪽 경계를 포인트라 부르는데, 마크와 포인트의
  위치는 C-x C-x 명령을 통해 서로 바꿀 수 있다. 마크 지정 명령을 두 번 반복하면
  포인트 위치에 마크가 지정된 후 선택 작업이 취소된다. 지정했던 마크들은 모두
  마크 스택에 저장되며 C-u C-SPC 명령을 통해 마크 스택에서 꺼낸 뒤 해당 위치로
  포인트를 옮길 수 있다.
  문서 전체를 선택할 때에는 C-x h 명령을 사용하면 되고, 포인트가 속한 문단을
  영역으로 잡을 때에는 M-h 명령을 사용하면 된다. 이 경우 포인트는 영역 시작으로
  이동하고, 끝부분에 마크가 설정된다. 영역 선택 전 포인트에서 마크를 스택에 미리
  넣어두면 명령 취소시 포인트를 이전 상태로 돌리는데 사용할 수 있다.

  윈도우에서 버퍼를 스크롤하는 편리한 방법 하나는 C-l 명령이다. 편집 중 처음 이
  명령에 대해서는 포인트가 있는 줄이 윈도우의 중앙에 위치하게 해주는데, 명령을
  반복하면 그 줄이 상단, 하단에 올 수 있게 버퍼를 그려준다. 이전 상태로 되돌려
  주지는 않는다. 윈도우 위 아래로 버퍼를 움직이는 명령은 C-v, M-v 이다. 잘 보면
  어느 방향으로 움직이더라도 그 방향의 두 번째 줄까지는 스크롤 후에도 확인할 수
  있다. 버퍼의 시작과 끝으로 포인트를 옮기기 위해서는 M-<, M-> 명령을 사용하면
  된다.

** 오늘의 명령 모음

   | Key       | Function                |
   |-----------+-------------------------|
   | C-SPC     | set-mark-command        |
   | C-x C-x   | exchange-point-and-mark |
   | C-u C-SPC |                         |
   | C-x h     | mark-whole-buffer       |
   | M-h       | mark-paragraph          |
   | C-l       | recenter-top-bottom     |
   | C-v       | scroll-up-command       |
   | M-v       | scroll-down-command     |
   | M-<       | beginning-of-buffer     |
   | M->       | end-of-buffer           |
