#+OPTIONS: whn:nil
* 2018-06-19

  단순한 검색은 C-s 명령 다음 검색어를 입력하면 된다. 검색어와 일치하는 대상은
  강조되어 보여지고 C-s 를 반복할 때마다 다음 대상으로 이동한다. 이전 위치로
  이동하고 싶을 때에는 C-r 명령을 사용할 수 있다. 처음부터 C-r 로 검색해도 된다.
  해당 위치에서 검색을 마치고 싶을 때에는 RET 키를 누르면 된다. C-g 명령으로
  검색을 취소한 경우 검색 전에 있던 포인트로 돌아간다. 정규 표현식을 사용해서
  찾기 시작하려면 Meta 키를 조합하여 C-M-s, C-M-r 로 명령을 호출하면 된다. 검색
  중 언제라도 M-p, M-n 으로 히스토리에 있는 검색어를 사용할 수 있다. 검색어와
  일치하는 대상들을 바꾸고 싶을 때에는 M-% 명령을 사용해서 미니버퍼에 내용을
  입력해주면 된다. 검색 결과에 대해 치환 여부를 물어볼 때 y, n 키를 통해 하나씩
  바꾸거나 넘어갈 수 있다. ? 키로 모두 치환이나 되돌리기 등의 다른 기능들의
  도움말을 볼 수 있다. 정규표현식을 사용해서 바꾸는 명령은 M-C-% 인데 바인딩 된
  키 입력이 불편할 때에는 M-x 명령으로 query-replace-regexp 를 직접 호출한다.

  숫자를 사용하여 특정 줄로 포인트를 옮기고 싶을 때에는 M-g g 명령을 사용한다.
  잘 쓰이진 않지만 줄 대신 글자를 단위로 사용하는 M-g c 명령도 있다.

** 오늘의 명령 모음

   | Key   | Function                |
   |-------+-------------------------|
   | C-s   | isearch-forward         |
   | C-r   | isearch-backward        |
   | C-M-s | isearch-forward-regexp  |
   | C-M-r | isearch-backward-regexp |
   | M-%   | query-replace           |
   | M-C-% | query-replace-regexp    |
   | M-g g | goto-line               |
   | M-g c | goto-char               |
